//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Votaciones
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class Semanas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    	
        public Semanas()
        {
            this.SemanaComensal = new HashSet<SemanaComensal>();
            this.VotacionesSemanales = new HashSet<VotacionesSemanales>();
        }
    
        public int idSemana { get; set; }
        public string nombre { get; set; }
        public System.DateTime fechaIni { get; set; }
        public System.DateTime fechaFin { get; set; }
        public int numSemana { get; set; }
        public bool cerrada { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SemanaComensal> SemanaComensal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VotacionesSemanales> VotacionesSemanales { get; set; }
    }
}
