//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Votaciones
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class SemanaInforme
    {
        public int idSemanaInforme { get; set; }
        public int numSemana { get; set; }
        public Nullable<int> idComensal_Alfa { get; set; }
        public Nullable<int> idComensal_Omega { get; set; }
        public Nullable<int> idRestaurante_Ganador { get; set; }
    }
}
