//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Votaciones
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class VotacionesSemanales
    {
        public int idVotacion { get; set; }
        public int idComensal { get; set; }
        public int idBar { get; set; }
        public int idSemana { get; set; }
        public bool votacion { get; set; }
        public bool vetacion { get; set; }
    
        public virtual Bar Bar { get; set; }
        public virtual Comensales Comensales { get; set; }
        public virtual Semanas Semanas { get; set; }
    }
}
